/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StandardsRouteImport } from './routes/standards'
import { Route as SkillsSlugRouteImport } from './routes/skills.$slug'
import { Route as StandardsIndexRouteImport } from './routes/standards.index'
import { Route as StandardsSlugRouteImport } from './routes/standards.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StandardsRoute = StandardsRouteImport.update({
  id: '/standards',
  path: '/standards',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsSlugRoute = SkillsSlugRouteImport.update({
  id: '/skills/$slug',
  path: '/skills/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const StandardsIndexRoute = StandardsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StandardsRoute,
} as any)
const StandardsSlugRoute = StandardsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => StandardsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/standards': typeof StandardsRouteWithChildren
  '/skills/$slug': typeof SkillsSlugRoute
  '/standards/$slug': typeof StandardsSlugRoute
  '/standards/': typeof StandardsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/skills/$slug': typeof SkillsSlugRoute
  '/standards/$slug': typeof StandardsSlugRoute
  '/standards': typeof StandardsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/standards': typeof StandardsRouteWithChildren
  '/skills/$slug': typeof SkillsSlugRoute
  '/standards/$slug': typeof StandardsSlugRoute
  '/standards/': typeof StandardsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/standards' | '/skills/$slug' | '/standards/$slug' | '/standards/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/skills/$slug' | '/standards/$slug' | '/standards'
  id:
    | '__root__'
    | '/'
    | '/standards'
    | '/skills/$slug'
    | '/standards/$slug'
    | '/standards/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  StandardsRoute: typeof StandardsRouteWithChildren
  SkillsSlugRoute: typeof SkillsSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/standards': {
      id: '/standards'
      path: '/standards'
      fullPath: '/standards'
      preLoaderRoute: typeof StandardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills/$slug': {
      id: '/skills/$slug'
      path: '/skills/$slug'
      fullPath: '/skills/$slug'
      preLoaderRoute: typeof SkillsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/standards/': {
      id: '/standards/'
      path: '/'
      fullPath: '/standards/'
      preLoaderRoute: typeof StandardsIndexRouteImport
      parentRoute: typeof StandardsRoute
    }
    '/standards/$slug': {
      id: '/standards/$slug'
      path: '/$slug'
      fullPath: '/standards/$slug'
      preLoaderRoute: typeof StandardsSlugRouteImport
      parentRoute: typeof StandardsRoute
    }
  }
}

interface StandardsRouteChildren {
  StandardsSlugRoute: typeof StandardsSlugRoute
  StandardsIndexRoute: typeof StandardsIndexRoute
}

const StandardsRouteChildren: StandardsRouteChildren = {
  StandardsSlugRoute: StandardsSlugRoute,
  StandardsIndexRoute: StandardsIndexRoute,
}

const StandardsRouteWithChildren = StandardsRoute._addFileChildren(
  StandardsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  StandardsRoute: StandardsRouteWithChildren,
  SkillsSlugRoute: SkillsSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
